# Site Settings
title: My Resume
url: 'https://nobodyme.github.io/'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Naveen Kumar
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'To enhance the quality of work of human beings without degrading the environment and life of other beings and to acquire knowledge in doing such works and strive for excellence.'

#sidebar links
email: naveenkumarspa@gmail.com
phone: 8438473753
github: github/nobodyme
medium: medium/@naveenkumarspa
#Update all the sections by editing the files inside _data folder.

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
